version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-name: "bevy"
      - dependency-name: "rand"
      - dependency-name: "serde"
      - dependency-name: "serde_json"
    groups:
      all-cargo:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-actions:
        patterns:
          - "*"
