[package]
name = "klotzkoepfe"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
description = "Klotzkoepfe"

[package.metadata.deb]
maintainer = "xi72yow <xi72yow@github.com>"
section = "games"
priority = "optional"
depends = "libasound2, libudev1, libwayland-client0, libxkbcommon0"
assets = [
    ["target/dist/klotzkoepfe", "usr/bin/", "755"],
]

[dependencies]
bevy = { version = "0.19", features = ["wav"] }
rand = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
# Dev-Builds: schnell, ohne LTO/Strip

# Distribution Build: cargo build --profile dist
[profile.dist]
inherits = "release"
strip = true
lto = true

# Schnellere Kompilierung im Dev
[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3
